# Based on the template in https://github.com/FedericoPonzi/rust-ci
name: Build binaries

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      skipBinStrip:
        description: 'Skip strip and upx'
        required: false
        default: 'false'
        type: boolean

jobs:
  check-client-id:
    name: Check if imgur client id secret exist
    runs-on: ubuntu-latest
    env:
      IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
    steps:
      - name: A/B Check
        if: ${{ env.IMGUR_CLIENT_ID == ''}}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('IMGUR_CLIENT_ID secret not set!')
  style:
    name: Check Style
    needs: [check-client-id]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: cargo fmt -- --check
        run: cargo fmt --all -- --check

  create-release:
    name: deploy
    needs: [style]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64-pc-windows-gnu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Build target
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          args: --release --locked
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}

      - name: Strip binary
        if: ${{ inputs.skipBinStrip != 'true'}}
        run: strip "target/${{ matrix.target }}/release/imgur-uploader.exe"

      - name: Run UPX to reduce binary size
        uses: crazy-max/ghaction-upx@v3
        if: ${{ inputs.skipBinStrip != 'true'}}
        with:
          version: latest
          files: 'target/${{ matrix.target }}/release/imgur-uploader.exe'
          args: -q

      - name: Publish
        if: github.event_name != 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
            files: 'target/${{ matrix.target }}/release/imgur-uploader.exe'

      - name: Upload artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: imgur-uploader.exe
          path: 'target/${{ matrix.target }}/release/imgur-uploader.exe'
